// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf3tFjAQFDhbBx-oN-aI_U0eSJQMarUyg',
    appId: '1:352762536946:android:4b48cccb4d1661e8c5016b',
    messagingSenderId: '352762536946',
    projectId: 'plants-spotify',
    storageBucket: 'plants-spotify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5K1LFdAdfTLH49y38LITTgab2J2yTZBc',
    appId: '1:352762536946:ios:917466951380d2fcc5016b',
    messagingSenderId: '352762536946',
    projectId: 'plants-spotify',
    storageBucket: 'plants-spotify.firebasestorage.app',
    androidClientId: '352762536946-97n3s3kkbpo70su0l0ep58ovndm85bub.apps.googleusercontent.com',
    iosClientId: '352762536946-q2b21e5ite92122k076lnfgd9lfd0d49.apps.googleusercontent.com',
    iosBundleId: 'com.plant.spotify',
  );

}